[build]
  publish = "build/"
  command = "yarn build"

[context.production.environment]
  NODE_ENV = "production"
  API_ENDPOINT = "https://predictionballs-api.herokuapp.com"

[context.stage.environment]
  NOVE_ENV = "stage"
  API_ENDPOINT = "https://predictionballs-api-stage.herokuapp.com"

[context.deploy-preview.environment]
  NOVE_ENV = "dev"
  REACT_APP_API_ENDPOINT = "https://predictionballs-api-stage.herokuapp.com/api"

[[redirects]]
  from = "/api/*"
  to = "{REACT_APP_API_ENDPOINT}/:splat"
  status = 200

[[redirects]]
  from = "/dogecoin/prediction"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
