[build]
  publish = "build/"
  command = "yarn build"

[context.production.environment]
  REACT_APP_ENV = "production"

[context.stage.environment]
  REACT_APP_ENV = "staging"

[context.deploy-preview.environment]
  REACT_APP_ENV = "staging"

[[redirects]]
  from = "/api-stage/*"
  to = "https://predictionballs-api-stage.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://predictionballs-api.herokuapp.com/api/:splat"
  status = 200

[[redirects]]
  from = "/dogecoin/prediction"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/dogecoin/prediction/widget"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
